basePath: /
definitions:
  models.Agenda:
    properties:
      group_id:
        type: string
      ical_url:
        type: string
      id:
        type: integer
    type: object
  models.User:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
info:
  contact:
    email: justine.bachelard@ext.uca.fr
    name: Justine Bachelard.
  description: API to manage users.
  title: middleware/example
  version: 1.0.0
paths:
  /agendas:
    delete:
      description: Delete all agendas from the database
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete all agendas
      tags:
      - agendas
    get:
      description: Retrieve all agendas
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Agenda'
            type: array
      summary: Get all agendas
      tags:
      - agendas
    post:
      consumes:
      - application/json
      description: Add a new agenda to the database
      parameters:
      - description: Agenda info
        in: body
        name: agenda
        required: true
        schema:
          $ref: '#/definitions/models.Agenda'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Agenda'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new agenda
      tags:
      - agendas
  /users:
    get:
      description: Get all users.
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "500":
          description: Something went wrong
      summary: Get all users.
      tags:
      - users
  /users/{id}:
    get:
      description: Get a user.
      parameters:
      - description: User UUID formatted ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "422":
          description: Cannot parse id
        "500":
          description: Something went wrong
      summary: Get a user.
      tags:
      - users
schemes:
- http
swagger: "2.0"
